### ISSUE TITLE
Команда добавления еды в кормушку иногда обрабатывается неправильно

### ISSUE THREAD

**Issue by vpolikarpov** [Ecialo/mauricio#13]
Если команда включает в себя имя бота, но не написано, что именно добавляется в кормушку, то в качестве названия еды будет выбрано имя бота. 

![изображение](https://user-images.githubusercontent.com/8066413/78467573-b782a600-7716-11ea-9117-d64bdd71fefb.png)

**Comment by anime-memes** [comment]
Я возьму
