### ISSUE TITLE
Кот боится людей без фамилии и неправильно их называет

### ISSUE THREAD

**Issue by ghost** [Ecialo/mauricio#17]
Если в телеграме у пользователя не указана фамилия, то с котом не получится ничего сделать, кроме как назвать (Саня может досыпать сюда логи от падения).

**Comment by Ecialo** [comment]
Мне казалось я исправил это в dc2d49ecc044043d18de4e48acef9caa9f104d33. И с тех пор проблема о себе знать не давала. Дай знать если воспроизведётся снова.

**Comment by ghost** [comment]
исправил, да. но мне не нравится решение, которое берёт и меняет мои фио:
```
ya, [16.04.20 14:09]
Миу

Котик, [16.04.20 14:09]
Котeйке нравится имя Миу

ya, [16.04.20 14:09]
/add_to_feeder корм

Котик, [16.04.20 14:09]
ya Anonych добавил корм в кормушку.
```
предлагаю по-честному только имя писать в таком случае
