### ISSUE TITLE
Слишком активный кот всё съел, быстро похудел и убежал

### ISSUE THREAD

**Issue by ghost** [Ecialo/mauricio#22]
Кот весил 5 килограмм. Перед отходом игрока ко сну кормушка кота была практически полной, но из-за очень большой надоедливости он всё съел, при этом потолстев на пару килограмм, а потом очень быстро похудел и убежал — навсегда. Всё это заняло около 4 часов, хронология: https://imgur.com/a/7lCoH4u

Это плохо, потому что мы наказываем пользователя и не даём ему ничего исправить.

**Comment by Ecialo** [comment]
Не вижу проблемы. На старте настройки такие, что кот жрёт примерно раз в 4 часа, а его вес меняется и того реже, примерно раз в 11 часов. Чтобы произошла описанная ситуация нужно сознательно выкрутить надоедливость в максимум и забить на кота.

**Comment by anime-memes** [comment]
Мне кажется, что в нормальном чате высокую надоедливость кота исправит кто-то, кого заебут сообщения через каждые три минуты. А так: если кот быстро ест, то надо быстро накладывать корм в кормушку

**Comment by ghost** [comment]
я не могу согласиться с тем, что в прямом смысле уйти спать, обеспечив кота едой, а потом обнаружить, что его нет, означает «забить». если он убегает за четыре часа, мне, получается, надо каждые три-четыре часа просыпаться?
кроме того, давайте будем честными: из высокой надоедливости никак не следует высокий метаболизм, это особенность реализации.

**Comment by Ecialo** [comment]
Весь смысл надоедливости/ленивости в том, чтобы настраивать частоту проявления кота под себя. Если не трогать настройки ленивости, то ты никогда не столкнёшься с той проблемой, которую расписываешь.

> если он убегает за четыре часа, мне, получается, надо каждые три-четыре часа просыпаться?

Нет. Тебе нужно сделать кота более ленивым или не делать его таким надоедливым. И спать полноценные 8 часов :о)

> кроме того, давайте будем честными: из высокой надоедливости никак не следует высокий метаболизм, это особенность реализации.

А из высокого метаболизма может следовать надоедливость. Ты же не знаешь, что именно происходит с котом. Ты только _чувствуешь_, что он стал ленивее или надоедливее.

**Comment by vpolikarpov** [comment]
> Тебе нужно сделать кота более ленивым или не делать его таким надоедливым

Получается, настолько высокий уровень надоедливости банально не имеет смысла. Возможно, максимальный уровень должен быть ниже?

**Comment by ghost** [comment]
пришли к идее, что, когда кот максимально худеет, он не убегает сразу, а обижается, и с ним можно в течение нескольких часов попробовать помириться:
```
ya, [20.04.20 19:19]
я понимаю. почему бы не дать в таком случае последний шанс? если кот тощий, пусть он подождёт, не знаю, какое-то разумное обозримое время (6 часов, к примеру), за которое его могли бы покормить и погладить

Саня, [20.04.20 19:22]
надо только подумать как с ним мириться, и где он находит килограмм

ya, [20.04.20 19:22]
ну, всем известно, что когда ты грустишь, то толстеешь, значит, килограмм не проблема

ya, [20.04.20 19:22]
а помириться — положить еды, обнять, погладить много-много раз

Саня, [20.04.20 19:35]
можно будет какую-нибудь отдельную механику под это придумать
```

**Comment by Ecialo** [comment]
> > Тебе нужно сделать кота более ленивым или не делать его таким надоедливым
> 
> Получается, настолько высокий уровень надоедливости банально не имеет смысла. Возможно, максимальный уровень должен быть ниже?

Мне он был полезен в 2 случаях:
* Во время отладки
* Когда я пытался по быстрому показать что умеет кот.

**Comment by vpolikarpov** [comment]
Пользователя, я думаю, не интересует, для чего тебе, как разработчику, может быть полезно такое значение надоедливости. Но, очевидно, ни отладка, ни демонстрация ему не нужны.

Я думаю, что обозначенные тобой проблемы можно решить иначе, не ставя пользователя в неловкое положение:
- Повышенный предел надоедливости вполне может быть различным для прода и dev/test. И на проде его стоит выставлять таким, чтобы было удобно пользователю.
- Для демонстрации же можно использовать специальную недокументированную команду (своеобразный чит такой).

**Comment by vpolikarpov** [comment]
> пришли к идее, что, когда кот максимально худеет, он не убегает сразу, а обижается, и с ним можно в течение нескольких часов попробовать помириться

В рамках обсуждения это выглядит как борьба с последствиями. Но в целом (не применительно к решению проблемы) идея мне нравится.

**Comment by Ecialo** [comment]
> Повышенный предел надоедливости вполне может быть различным для прода и dev/test. И на проде его стоит выставлять таким, чтобы было удобно пользователю.


"Удобно пользователю" это сколько? Допустим мы сделаем так, чтобы на пределе он был вдвое менее надоедливым. Через неделю у Вани найдётся ещё один приятель, которому будет слишком быстро. Мы опять замедлим кота. Потом найдётся чувак, которому этот предел будет слишком медленный. Должны ли мы в этом случае менять предел в сторону ускорения?

Это всё очень напоминает обсуждения вида:
* Игра слишком сложная на максимальной сложности, я не могу её пройти.
* Наушники слишком громкие на максимальной громкости, я не могу их слушать.
* Вода слишком горячая на максимальной температуре, я не могу ей обливаться.

В итоге:
* Я против изменения пределов. 
* Мне нравится идея с последним шансом
* Можно дописать в сообщения об изменениях надоедливости то, раз в сколько кот будет меняться.

**Comment by vpolikarpov** [comment]
Во всех случаях, с которыми ты сравниваешь, пользователь понимает, чего можно ожидать: он понимает, что игра может стать слишком сложной, музыка слишком громкой, а вода слишком горячей. Но из повышения надоедливости кота никак не следует то, что он может внезапно свалить навсегда, пока ты спишь: такое следствие не очевидна для пользователя, который не знаком с внутренней логикой бота.

**Comment by Ecialo** [comment]
Кот может свалить при любой надоедливости. То что кот может закончиться при 0 весе, кажется, довольно очевидно из бытовой логики, наличия веса у бота и сообщениях о похудании. Можно добавить это в `/help`, если это действительно вызывает проблемы.

**Comment by vpolikarpov** [comment]
> Кот может свалить при любой надоедливости.

Ты приводил раньше сравнение с играми. Так вот, проиграть тоже можно при любой сложности. Вопрос не в возможности, а в ожидании пользователя. На большой сложности игры игрок ожидает того, что ему может быть сложно. А вот ожидания от надоедливого кота ограничиваются только тем, что он будет много сообщений писать, а то, что скорость похудения связана с надоедливостью, совершенно не очевидно.

**Comment by Ecialo** [comment]
Окей, я понял что это не очевидно. Тогда сделаем очевиднее. Ну и последний шанс тоже сделаем. Я закрываю этот тикет и вечером сделаю парочку по мотивам.
