### ISSUE TITLE
Сообщения можно немного разнообразить, выбирая подлежащее случайным образом

### ISSUE THREAD

**Issue by vpolikarpov** [Ecialo/mauricio#33]
Сейчас в сообщениях захардкожена либо подстановка клички кота, либо одно из слов "кот", "котик", "котяра". "котeйка". Сообщения выглядели бы разнообразнее и интереснее, если туда подставлялось бы случайное слово (или кличка).

Например, сообщение `<%= cat.name %> навернул от души!` получило бы сразу ещё четыре вариации:
- `Кот навернул от души!`
- `Котик навернул от души!`
- `Котяра навернул от души!`
- `Котeйка навернул от души!`

Аналогично можно сделать и с другими частями предложения (но тут уже придётся обойтись без клички, так как падеж не именительный), например:
- `<%= Member.full_name(who) %> гладит кота.`
- `<%= Member.full_name(who) %> гладит котика.`
- `<%= Member.full_name(who) %> гладит котяру.`
- `<%= Member.full_name(who) %> гладит котейку.`

**Comment by Ecialo** [comment]
Мне нравится! Обязательно сделаем!
